version: "2"

linters:
  default: standard
  enable:
    - cyclop
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - gofumpt
    - goimports

linters-settings:
  whitespace:
    multi-func: true
  goimports:
    local-prefixes: gorm.io/gorm

