linters:
  disable:
    - cyclop
    - errcheck
    - gosec
    - ineffassign
    - staticcheck
    - structcheck
  enable:
    - errorlint
    - exportloopref
    - gci 
    - gocritic
    - gofumpt
    - misspell
    - prealloc
    - unconvert
    - unparam
issues:  
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  exclude-rules:
  - linters:
      - gocritic
    text: "singleCaseSwitch"
  - linters:
      - gocritic
    text: "ifElseChain"
linters-settings:
  gci:
    local-prefixes: gorm.io/gorm