package migrator

// dialectTypeAliases holds type aliases for different SQL dialects
// make sure you map in both directions!
var dialectTypeAliases = map[string]map[string][]string{
	"postgres": {
		"varchar":           {"character varying"},
		"character varying": {"varchar"},
		"integer":           {"int", "int4"},
		"int":               {"integer", "int4"},
		"int4":              {"integer", "int"},
		"bigint":            {"int8"},
		"int8":              {"bigint"},
		"smallint":          {"int2"},
		"int2":              {"smallint"},
		"character":         {"char"},
		"char":              {"character"},
		"real":              {"float4"},
		"float4":            {"real"},
		"double":            {"float8", "double precision"},
		"float8":            {"double", "double precision"},
		"double precision":  {"double", "float8"},
		"boolean":           {"bool"},
		"bool":              {"boolean"},
		"timestamp":         {"timestamp without time zone"},
		"timestamptz":       {"timestamp with time zone"},
		"text":              {"varchar"},
		"json":              {"jsonb"},
		"jsonb":             {"json"},
	},
	"mysql": {
		"varchar":    {"varchar"},
		"int":        {"integer", "int"},
		"integer":    {"int", "integer"},
		"bool":       {"boolean", "tinyint(1)"},
		"boolean":    {"bool", "tinyint(1)"},
		"tinyint(1)": {"bool", "boolean"},
		"text":       {"text"},
		"mediumtext": {"text"},
		"longtext":   {"text"},
		"datetime":   {"timestamp"},
		"timestamp":  {"datetime"},
	},
	"sqlite": {
		// SQLite has loose typing, so fewer strict aliases
		"varchar": {"text", "varchar"},
		"text":    {"varchar", "text"},
		"integer": {"int", "integer"},
		"int":     {"integer", "int"},
		"real":    {"float", "double", "real"},
		"float":   {"real", "double", "float"},
		"double":  {"real", "float", "double"},
		"boolean": {"integer"}, // SQLite stores booleans as integers
		"bool":    {"integer"},
	},
	"sqlserver": {
		"varchar":   {"nvarchar", "varchar"},
		"nvarchar":  {"varchar", "nvarchar"},
		"int":       {"integer", "int"},
		"integer":   {"int", "integer"},
		"bit":       {"boolean", "bool"},
		"boolean":   {"bit", "bool"},
		"bool":      {"bit", "boolean"},
		"datetime":  {"datetime2", "timestamp"},
		"datetime2": {"datetime", "timestamp"},
		"timestamp": {"datetime", "datetime2"},
		"ntext":     {"text", "ntext"},
		"text":      {"ntext", "text"},
	},
	"gaussdb": {
		// GaussDB is PostgreSQL-compatible
		"varchar":           {"character varying"},
		"character varying": {"varchar"},
		"integer":           {"int", "int4"},
		"int":               {"integer", "int4"},
		"int4":              {"integer", "int"},
		"bigint":            {"int8"},
		"int8":              {"bigint"},
		"smallint":          {"int2"},
		"int2":              {"smallint"},
		"character":         {"char"},
		"char":              {"character"},
		"real":              {"float4"},
		"float4":            {"real"},
		"double":            {"float8", "double precision"},
		"float8":            {"double", "double precision"},
		"double precision":  {"double", "float8"},
		"boolean":           {"bool"},
		"bool":              {"boolean"},
		"timestamp":         {"timestamp without time zone"},
		"timestamptz":       {"timestamp with time zone"},
		"text":              {"varchar"},
	},
}
